name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            target: x86_64-unknown-linux-gnu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--release"

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp target/${{ matrix.platform.target }}/release/stormbreaker artifacts/stormbreaker-${{ matrix.platform.target }}
          cd artifacts
          tar -czvf stormbreaker-${{ matrix.platform.target }}.tar.gz stormbreaker-${{ matrix.platform.target }}
          shasum -a 256 stormbreaker-${{ matrix.platform.target }}.tar.gz > stormbreaker-${{ matrix.platform.target }}.tar.gz.sha256

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stormbreaker-${{ matrix.platform.target }}
          path: artifacts/*

  create-release:
    name: Create Release
    needs: build-and-release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Get tag name
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ steps.get_tag.outputs.TAG }}
          draft: false
          prerelease: false
          files: |
            artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
